---
title: "Matching and Subclassification"
author: "Moritz Seefeldt"
---

# Assignment 1
```{r}
df <- readRDS(("data/membership.rds"))

dag_model <- 'dag {
bb="0,0,1,1"
Card [exposure,pos="0.075,0.4"]
Avg_purch [outcome,pos="0.4,0.4"]
Age [pos="0.1,0.2"]
Sex [pos="0.35,0.2"]
Pre_avg_purch [pos="0.2,0.6"]
Card -> Avg_purch
Pre_avg_purch -> Avg_purch
Pre_avg_purch -> Card
Age -> Card
Age -> Pre_avg_purch
Sex -> Card
Sex -> Pre_avg_purch
}
'
# draw DAG
ggdag_status(dag_model) +
  guides(fill = "none", color = "none") +  # Disable the legend
  geom_dag_edges(edge_color = "white")
```
# Assignment 2
Please find the model summary at the end of this document.
```{r}
model <- lm(avg_purch ~ card, data = df)
summary(model)
```
# Assignment 3
```{r}
cem <- matchit(card ~ pre_avg_purch + age + sex,
               data = df, 
               method = 'cem', 
               estimand = 'ATE')
df_cem = match.data(cem)
model_cem <- lm(avg_purch ~ card, data = df_cem, weights = weights)
summary(model_cem)

nn <- matchit(card ~ pre_avg_purch + age + sex,
              data = df,
              method = "nearest",
              distance = "mahalanobis",
              replace = T)
df_nn <- match.data(nn)
model_nn <- lm(avg_purch ~ card, data = df_nn, weights = weights)
summary(model_nn)


model_prop <- glm(card ~ pre_avg_purch + age + sex,
                  data = df,
                  family = binomial(link = "logit"))
df_aug <- df %>% mutate(propensity = predict(model_prop, type = "response"))

# Extend data by IPW scores
df_ipw <- df_aug %>% mutate(
  ipw = (card/propensity) + ((1-card) / (1-propensity)))


model_ipw <- lm(avg_purch ~ card,
                data = df_ipw, 
                weights = ipw)
summary(model_ipw)

model_ipw_trim <- lm(avg_purch ~ card,
                     data = df_ipw %>% filter(propensity %>% between(0.15, 0.85)),
                     weights = ipw)
summary(model_ipw_trim)

modelsummary::modelsummary(list("Naive" = model,
                                "CEM"  = model_cem,
                                "NN"    = model_nn,
                                "IPW1"  = model_ipw,
                                "IPW2"  = model_ipw_trim))

```