{
  "hash": "f10620b41b905bbb7bfbcd190c4ed547",
  "result": {
    "markdown": "---\ntitle: \"Randomized Controlled Trials\"\nauthor: \"Moritz Seefeldt\"\n---\n\n\n# Assignment 1\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-1_967f15125461ea5372d1ee4e2775430d'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> \n#> Attache Paket: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Die folgenden Objekte sind maskiert von 'package:stats':\n#> \n#>     filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Die folgenden Objekte sind maskiert von 'package:base':\n#> \n#>     intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\ndf <- readRDS((\"data/abtest_online.rds\"))\n\nstr(df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> tibble [1,000 × 6] (S3: tbl_df/tbl/data.frame)\n#>  $ ip             : chr [1:1000] \"161.88.211.70\" \"239.86.201.0\" \"35.90.22.130\" \"219.176.193.3\" ...\n#>  $ chatbot        : logi [1:1000] TRUE TRUE TRUE FALSE TRUE TRUE ...\n#>  $ previous_visit : num [1:1000] 0 1 1 4 1 2 1 1 1 0 ...\n#>  $ mobile_device  : logi [1:1000] FALSE FALSE FALSE TRUE FALSE FALSE ...\n#>  $ purchase       : num [1:1000] 0 1 0 0 0 0 1 1 0 0 ...\n#>  $ purchase_amount: num [1:1000] 0 39.5 0 0 0 ...\n```\n:::\n\n```{.r .cell-code}\ncompare_device <- ggplot(df, aes(x = chatbot, y = after_stat(count), fill = mobile_device)) +\n  stat_count(geom = \"bar\", position = \"dodge\") +\n  labs(x = \"Chatbot\", y = \"Number of users\", title = \"Number of users on mobile devices\") +\n  scale_fill_manual(values = c(\"FALSE\" = \"blue\", \"TRUE\" = \"red\")) +\n  theme_minimal()\n\ncompare_previous <- \n  ggplot(df, \n         aes(x = chatbot, \n             y = previous_visit, \n             color = as.factor(chatbot))) +\n  stat_summary(geom = \"errorbar\", \n               width = .5,\n               fun.data = \"mean_se\", \n               fun.args = list(mult=1.96),\n               show.legend = F) +\n  labs(x = NULL, y = \"Previous visits\", title = \"Difference in previous visits\")\n\ncompare_device\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncompare_previous\n```\n\n::: {.cell-output-display}\n![](06_rct_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n\n```{.r .cell-code}\nmean_previous_visits <- df %>%\n  group_by(chatbot) %>%\n  summarize(mean_previous_visits = mean(previous_visit))\n\nprint(mean_previous_visits)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> # A tibble: 2 × 2\n#>   chatbot mean_previous_visits\n#>   <lgl>                  <dbl>\n#> 1 FALSE                   2.17\n#> 2 TRUE                    1.88\n```\n:::\n:::\n\nI would argue the covariates are somewhat balanced across the groups, as can be seen from the plots. However, there is a slight difference in the number of previous visits (mean 2.17 vs. 1.88). \n\n# Assignment 2\n\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-2_ebd88eeb46d71d9f2ac0812e5a086592'}\n\n```{.r .cell-code}\nmodel_purchase_amount <- lm(purchase_amount ~ chatbot, data = df)\nsummary(model_purchase_amount)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = purchase_amount ~ chatbot, data = df)\n#> \n#> Residuals:\n#>     Min      1Q  Median      3Q     Max \n#> -16.702 -14.478  -9.626  13.922  64.648 \n#> \n#> Coefficients:\n#>             Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)  16.7017     0.8374  19.944  < 2e-16 ***\n#> chatbotTRUE  -7.0756     1.1796  -5.998 2.79e-09 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 18.65 on 998 degrees of freedom\n#> Multiple R-squared:  0.0348,\tAdjusted R-squared:  0.03383 \n#> F-statistic: 35.98 on 1 and 998 DF,  p-value: 2.787e-09\n```\n:::\n:::\n\n\n# Assignment 3\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-3_6c39ad064170594cfa88ee9c119d2d4d'}\n\n```{.r .cell-code}\nmodel_purchase_mobile <- lm(purchase_amount ~ chatbot * mobile_device, data = df)\nsummary(model_purchase_mobile)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> lm(formula = purchase_amount ~ chatbot * mobile_device, data = df)\n#> \n#> Residuals:\n#>    Min     1Q Median     3Q    Max \n#> -16.98 -14.54  -9.95  14.13  65.24 \n#> \n#> Coefficients:\n#>                               Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)                    16.9797     1.0152  16.725   <2e-16 ***\n#> chatbotTRUE                    -7.0301     1.4284  -4.922    1e-06 ***\n#> mobile_deviceTRUE              -0.8727     1.7987  -0.485    0.628    \n#> chatbotTRUE:mobile_deviceTRUE  -0.1526     2.5369  -0.060    0.952    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Residual standard error: 18.66 on 996 degrees of freedom\n#> Multiple R-squared:  0.03534,\tAdjusted R-squared:  0.03244 \n#> F-statistic: 12.16 on 3 and 996 DF,  p-value: 8.034e-08\n```\n:::\n:::\n\n\n# Assignment 4\n\n::: {.cell hash='06_rct_cache/html/unnamed-chunk-4_e6c830b4487a50d604d37b167b5972c7'}\n\n```{.r .cell-code}\nmodel_purchase <- glm(purchase ~ chatbot, family=binomial(link='logit'), data = df)\nsummary(model_purchase)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> \n#> Call:\n#> glm(formula = purchase ~ chatbot, family = binomial(link = \"logit\"), \n#>     data = df)\n#> \n#> Coefficients:\n#>             Estimate Std. Error z value Pr(>|z|)    \n#> (Intercept) -0.01613    0.08981  -0.180    0.857    \n#> chatbotTRUE -0.98939    0.13484  -7.337 2.18e-13 ***\n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> (Dispersion parameter for binomial family taken to be 1)\n#> \n#>     Null deviance: 1329.1  on 999  degrees of freedom\n#> Residual deviance: 1273.3  on 998  degrees of freedom\n#> AIC: 1277.3\n#> \n#> Number of Fisher Scoring iterations: 4\n```\n:::\n:::\n\nThe coefficient for the presence of the chatbot (-0,989) indicates that the probability of making a sale is drastically reduced (multiplied by exp(-0.989) =  0.3719485).",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}